Repository DarkflameUniverse/DarkflameServer, pull requests merged in 2022-02, with the labels that each got.

#348 Added logic to Convert UScore to Coins for Level 45 Characters
  dCommon/dCommonVars.h
  dGame/dComponents/CharacterComponent.cpp
  dGame/dGameMessages/GameMessages.cpp
  dGame/dGameMessages/GameMessages.h
  dGame/dMission/Mission.cpp
  dGame/dUtilities/SlashCommandHandler.cpp
  dZoneManager/dZoneManager.cpp
  dZoneManager/dZoneManager.h
Labels: status/waiting-on-review

#213 added tracking of Pet Excavator achievement
  dScripts/PetDigServer.cpp
  dScripts/PetDigServer.h
Labels: status/waiting-on-author

#251 Implement CDZoneTable PlayerLoseCoinsOnDeath
  dGame/dComponents/DestroyableComponent.cpp
  dZoneManager/dZoneManager.cpp
  dZoneManager/dZoneManager.h
Labels: status/waiting-on-author, status/waiting-on-review

#444 Fix Plunger Gun not being removed from inventory after completing mission
  dScripts/NpcCowboyServer.cpp
Labels: bug, S-waiting-on-review, A-scripts

#447 Fix spam-log on master disconnect
  dWorldServer/WorldServer.cpp
Labels: enhancement, S-waiting-on-review, A-world-server

#449 Rehook dPhysics to main framerate
  dWorldServer/PerformanceManager.cpp
  dWorldServer/PerformanceManager.h
  dWorldServer/WorldServer.cpp
Labels: S-waiting-on-playtest, A-physics
