Repository DarkflameUniverse/DarkflameServer, pull requests merged in 2022-01, with the labels that each got.

#352 Add windows CI
  .github/workflows/build-and-test.yml
  CMakeLists.txt
  CMakePresets.json
  tests/TestLDFFormat.cpp
  tests/TestNiPoint3.cpp
Labels: bug, enhancement, status/waiting-on-review

#353 Remove IP Logging
  dGame/UserManager.cpp
  dGame/dComponents/ScriptedActivityComponent.cpp
  dGame/dGameMessages/GameMessages.cpp
  dGame/dUtilities/SlashCommandHandler.cpp
Labels: status/waiting-on-review

#293 Fix issue #268 : wrong shirt colors in the character selection
  dGame/UserManager.cpp
  dGame/UserManager.h
Labels: status/waiting-on-review

#290 BoNS Time Smash Fix
  dScripts/ZoneNsWaves.cpp
Labels: status/waiting-on-playtest

#87 Add zone 1700 to list of accessible zones
  dGame/dUtilities/SlashCommandHandler.cpp
Labels: status/waiting-on-author

#339 Fix Area of Effect Behavior Targets
  dGame/dBehaviors/AreaOfEffectBehavior.cpp
  dGame/dBehaviors/AreaOfEffectBehavior.h
  dGame/dBehaviors/BehaviorContext.cpp
  dGame/dBehaviors/BehaviorContext.h
  dGame/dComponents/DestroyableComponent.cpp
  dGame/dComponents/DestroyableComponent.h
Labels: status/waiting-on-author, status/waiting-on-review
